//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtoiHomeManager.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ITextTransfer")]
    public interface ITextTransfer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextTransfer/GetRoot", ReplyAction="http://tempuri.org/ITextTransfer/GetRootResponse")]
        string GetRoot();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextTransfer/GetRoot", ReplyAction="http://tempuri.org/ITextTransfer/GetRootResponse")]
        System.Threading.Tasks.Task<string> GetRootAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextTransfer/GetData", ReplyAction="http://tempuri.org/ITextTransfer/GetDataResponse")]
        string GetData(string arg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextTransfer/GetData", ReplyAction="http://tempuri.org/ITextTransfer/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(string arg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITextTransferChannel : AtoiHomeManager.ServiceReference.ITextTransfer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TextTransferClient : System.ServiceModel.ClientBase<AtoiHomeManager.ServiceReference.ITextTransfer>, AtoiHomeManager.ServiceReference.ITextTransfer {
        
        public TextTransferClient() {
        }
        
        public TextTransferClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TextTransferClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextTransferClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextTransferClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetRoot() {
            return base.Channel.GetRoot();
        }
        
        public System.Threading.Tasks.Task<string> GetRootAsync() {
            return base.Channel.GetRootAsync();
        }
        
        public string GetData(string arg) {
            return base.Channel.GetData(arg);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string arg) {
            return base.Channel.GetDataAsync(arg);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ITextTransferSoap")]
    public interface ITextTransferSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextTransfer/GetRoot", ReplyAction="http://tempuri.org/ITextTransfer/GetRootResponse")]
        string GetRoot();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextTransfer/GetRoot", ReplyAction="http://tempuri.org/ITextTransfer/GetRootResponse")]
        System.Threading.Tasks.Task<string> GetRootAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextTransfer/GetData", ReplyAction="http://tempuri.org/ITextTransfer/GetDataResponse")]
        string GetData(string arg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextTransfer/GetData", ReplyAction="http://tempuri.org/ITextTransfer/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(string arg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextTransferSoap/DownloadImage", ReplyAction="http://tempuri.org/ITextTransferSoap/DownloadImageResponse")]
        System.IO.Stream DownloadImage(string strFilename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextTransferSoap/DownloadImage", ReplyAction="http://tempuri.org/ITextTransferSoap/DownloadImageResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> DownloadImageAsync(string strFilename);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITextTransferSoapChannel : AtoiHomeManager.ServiceReference.ITextTransferSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TextTransferSoapClient : System.ServiceModel.ClientBase<AtoiHomeManager.ServiceReference.ITextTransferSoap>, AtoiHomeManager.ServiceReference.ITextTransferSoap {
        
        public TextTransferSoapClient() {
        }
        
        public TextTransferSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TextTransferSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextTransferSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextTransferSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetRoot() {
            return base.Channel.GetRoot();
        }
        
        public System.Threading.Tasks.Task<string> GetRootAsync() {
            return base.Channel.GetRootAsync();
        }
        
        public string GetData(string arg) {
            return base.Channel.GetData(arg);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string arg) {
            return base.Channel.GetDataAsync(arg);
        }
        
        public System.IO.Stream DownloadImage(string strFilename) {
            return base.Channel.DownloadImage(strFilename);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> DownloadImageAsync(string strFilename) {
            return base.Channel.DownloadImageAsync(strFilename);
        }
    }
}
