//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtoiHomeManager.TestOneClickShotServiceSoap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TestOneClickShotServiceSoap.IOneClickShot")]
    public interface IOneClickShot {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOneClickShot/GetRoot", ReplyAction="http://tempuri.org/IOneClickShot/GetRootResponse")]
        string GetRoot();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOneClickShot/GetRoot", ReplyAction="http://tempuri.org/IOneClickShot/GetRootResponse")]
        System.Threading.Tasks.Task<string> GetRootAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOneClickShot/GetData", ReplyAction="http://tempuri.org/IOneClickShot/GetDataResponse")]
        string GetData(string arg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOneClickShot/GetData", ReplyAction="http://tempuri.org/IOneClickShot/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(string arg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOneClickShotChannel : AtoiHomeManager.TestOneClickShotServiceSoap.IOneClickShot, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OneClickShotClient : System.ServiceModel.ClientBase<AtoiHomeManager.TestOneClickShotServiceSoap.IOneClickShot>, AtoiHomeManager.TestOneClickShotServiceSoap.IOneClickShot {
        
        public OneClickShotClient() {
        }
        
        public OneClickShotClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OneClickShotClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OneClickShotClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OneClickShotClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetRoot() {
            return base.Channel.GetRoot();
        }
        
        public System.Threading.Tasks.Task<string> GetRootAsync() {
            return base.Channel.GetRootAsync();
        }
        
        public string GetData(string arg) {
            return base.Channel.GetData(arg);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string arg) {
            return base.Channel.GetDataAsync(arg);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TestOneClickShotServiceSoap.IOneClickShotSoap")]
    public interface IOneClickShotSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOneClickShot/GetRoot", ReplyAction="http://tempuri.org/IOneClickShot/GetRootResponse")]
        string GetRoot();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOneClickShot/GetRoot", ReplyAction="http://tempuri.org/IOneClickShot/GetRootResponse")]
        System.Threading.Tasks.Task<string> GetRootAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOneClickShot/GetData", ReplyAction="http://tempuri.org/IOneClickShot/GetDataResponse")]
        string GetData(string arg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOneClickShot/GetData", ReplyAction="http://tempuri.org/IOneClickShot/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(string arg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOneClickShotSoap/DownloadImage", ReplyAction="http://tempuri.org/IOneClickShotSoap/DownloadImageResponse")]
        System.IO.Stream DownloadImage(string strFilename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOneClickShotSoap/DownloadImage", ReplyAction="http://tempuri.org/IOneClickShotSoap/DownloadImageResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> DownloadImageAsync(string strFilename);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOneClickShotSoapChannel : AtoiHomeManager.TestOneClickShotServiceSoap.IOneClickShotSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OneClickShotSoapClient : System.ServiceModel.ClientBase<AtoiHomeManager.TestOneClickShotServiceSoap.IOneClickShotSoap>, AtoiHomeManager.TestOneClickShotServiceSoap.IOneClickShotSoap {
        
        public OneClickShotSoapClient() {
        }
        
        public OneClickShotSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OneClickShotSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OneClickShotSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OneClickShotSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetRoot() {
            return base.Channel.GetRoot();
        }
        
        public System.Threading.Tasks.Task<string> GetRootAsync() {
            return base.Channel.GetRootAsync();
        }
        
        public string GetData(string arg) {
            return base.Channel.GetData(arg);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string arg) {
            return base.Channel.GetDataAsync(arg);
        }
        
        public System.IO.Stream DownloadImage(string strFilename) {
            return base.Channel.DownloadImage(strFilename);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> DownloadImageAsync(string strFilename) {
            return base.Channel.DownloadImageAsync(strFilename);
        }
    }
}
